name: Cypress Tests

on: 
  workflow_dispatch:
    inputs:
      cli:
        description: Run by cypress command line
        default: yarn cypress run        

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
         wait-on: ${{ secrets.BASE_URL }}
        
      - name: Install dependencies
        run: yarn install
                
      - name: Run E2E tests
        run: ${{ github.event.inputs.cli }}
